<a href="https://colab.research.google.com/github/aishani1903/MyAssignments/blob/main/Assignment_8(Numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
print("Enter the entries in a single line (separated by space): ")

entries = list(map(int, input().split()))

matrix = np.array(entries).reshape(3,3)
print(matrix)


Enter the entries in a single line (separated by space): 


KeyboardInterrupt: ignored

In [ ]:
b = np.array([[0.5, 22.4, np.nan],[41, 52.5, np.nan]])
b

array([[ 0.5, 22.4,  nan],
       [41. , 52.5,  nan]])

b[2,2]

In [ ]:
a = b[~(np.isnan(b))]
a

array([ 0.5, 22.4, 41. , 52.5])

In [ ]:
arr = [20, 2, 7, 1, 34]

print("50th percentile of arr is: ", np.percentile(arr,50))
print("25th percentile of arr is: ", np.percentile(arr,25))
print("75th percentile of arr is: ", np.percentile(arr,75))

50th percentile of arr is:  7.0
25th percentile of arr is:  2.0
75th percentile of arr is:  20.0


In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
def sum(matrix):
  return np.sum(matrix, axis = 0)

print(sum(matrix))

[22 26 30]


In [ ]:
z = set('abc')
z.add('san')
z.update(set(['p','q']))
z

{'a', 'b', 'c', 'p', 'q', 'san'}

In [ ]:
print('abc. DEF'.capitalize())

Abc. def


In [ ]:
import regex as re

In [ ]:
string = 'a'
pattern = '\D'
a = re.findall(string, pattern)
print(a)

[]


In [ ]:
string = "Hello There"

pattern = "\s"

output = re.search(pattern, string)

if output:

  print("The characters have spaces in between")

else:

  print("The characters have spaces")

The characters have spaces in between


In [ ]:
string = "H3llo Th3r3"

pattern = "\d"

replace = "e"

output = re.sub(pattern, replace, string)

print(output)

Hello There


In [ ]:
pattern = '^a\w*t$'

string = 'arrest'

result = re.match(pattern, string)

if result:

  print("String matches with the patter.")

else:

  print("String does not match with the pattern.")

String matches with the patter.


In [ ]:
string = 'hell0 have a gr3at d4y!'

pattern = '(\d) (\D)'

match = re.search(pattern, string)

if match:

  print(match.group())

else:

  print("pattern not found")

0 h


In [ ]:
string = 'Hello There'

pattern = '\s'

output = re.split(pattern, string)

print(output)

['Hello', 'There']


In [ ]:
string = 'Test for printing \n escape sequence '

print(string)

result = re.findall(r'[\n]', string)

print(result)


Test for printing 
 escape sequence 
['\n']
